### PR TITLE
Remove html highlight

### PR DESCRIPTION
**Pull request by tyru**
Hi Stephan, Would you include this changes?
- remove html highlight. because I found that ":setfiletype html.ftl" is enough to do this...
- wrote v1.2 changelog. but I'm not the author. if you have uncommited changes for v1.2, you can ignore that commit.

Should I send an email to freemarker-devel if you would release v1.2 ?

### CODE REVIEW

**Comment by chaquotay** [comment]
Hi tyru,

because I'm neither actively involved in FreeMarker nor an active Vim user right now I'd like to pass the "release management" of ftl.vim to you, if that's okay.

**Comment by tyru** [comment]
ok, I will send an email to freemarker-devel.
thanks for your merge!

**Comment by tyru** [comment]
hmm, sorry, maybe I didn't understand what you said?
did you say me "do you become a maintainer of ftl.vim?"
I don't think about becoming a maintainer of ftl.vim
because also I might not be going to involve actively in those project.
I appreciate the thought. thanks.

**Comment by chaquotay** [comment]
Okay, then we will leave it the way it is: it's available via the FreeMarker website and is on GitHub. "Maintaining" it is not really an issue because ftl.vim doesn't change a lot.

**Pull request merged**
